variables:
  'system.debug': true

jobs:
- job: noncontainer
  steps:
  - task: Cache@0
    inputs:
      key: azure-pipelines.yml
      path: somefolder

- job: container
  container: ubuntu:16.04
  steps:
  - task: Cache@0
    inputs:
      key: azure-pipelines.yml
      path: somefolder
