pool:
  vmImage: 'ubuntu-16.04'

container: node:10.16.0-jessie

steps:
- bash: du -sh .

- bash: |
    echo "bsd: $(Build.SourcesDirectory)"
    echo "##vso[task.setvariable variable=foo]$(Build.SourcesDirectory)"

- task: Cache@0
  inputs:
    key: $(foo)/package.json
    path: node_modules

- bash: du -sh .

- bash: npm install