pool:
  vmImage: 'ubuntu-16.04'

container: node:10.16.0-jessie

steps:
- bash: du -sh .

- task: Cache@0
  inputs:
    key: |
      $(Build.SourcesDirectory)/package.json
      $[hash('yarn.lock')]
      $[hash('$(Build.SourcesDirectory)/yarn.lock')]
      s$[hash('$(Build.SourcesDirectory)/yarn.lock')]e
    path: node_modules

- bash: npm install